### ISSUE TITLE
[Back-End] Relações do banco de dados

### ISSUE THREAD

**Issue by biancafc** [leonardoscorza/stack_helper#15]
Criar a modelagem das relações do banco de dados, utilizar o seguinte modelo:

![captura de tela de 2016-10-05 09-41-04](https://cloud.githubusercontent.com/assets/6681745/19209724/84823d00-8ce7-11e6-83cc-5820be62d644.png)

- QUESTION: Onde vamos guardar as perguntas, uma question sempre tem um usuário (criador);
- ANWSER: São as respostas as perguntas, ou até mesmo respostas as respostas; 
- LIKE: São os likes da pergunta e também os likes da resposta (através de uma associação polimórfica), quando ele são likes de resposta nos ajudam a classificar essa resposta como correta ou não;
- HASHTAG: São como categorias, mas podem ser criadas dinamicamente pelos usuários para classificar suas perguntas e vão nos ajudar a notificar os desenvolvedores interessados em responder perguntas especificas;
- NOTIFICATION: Conecta os desenvolvedores as hashatgs que eles tem interesse e nos fala quando eles querem ser notificados para novas perguntas com essas hashtags.

**Comment by rauanfelipe** [comment]
Farei esta task.

**Comment by nenoalmeida** [comment]
@rauanfelipe se precisar de ajuda só falar

**Comment by rauanfelipe** [comment]
![models](https://cloud.githubusercontent.com/assets/14976415/19222391/b6afb748-8e2d-11e6-803a-746ba58e3f3d.png)

**Comment by rauanfelipe** [comment]
Quem tiver alguma dúvida ou sugestão pode comentar aqui ou falar no slack.

**Comment by rauanfelipe** [comment]
PR feito.
