### ISSUE TITLE
[Back-End] Adicionar arquivo de secrets no gitignore

### ISSUE THREAD

**Issue by betogrun** [leonardoscorza/stack_helper#24]
Atualizar o arquivo de secrets adicionando o arquivo secrets.yml.

**Comment by samuelrubens** [comment]
Beto, isso é para não precisar fazer o import das variaveis no ambiente local?

**Comment by betogrun** [comment]
@samuelrubens é para apenas ignorar o arquivo mesmo. Acho que precisaremos de outra issue para tratar o caso das variáveis locais, o que acha?
