### ISSUE TITLE
Definir plataforma de Triagem de tasks

### ISSUE THREAD

**Issue by samuelrubens** [leonardoscorza/stack_helper#27]
Minha sugestão é que usemos o:
https://www.codetriage.com
é simplesmente completo, acessem e tirem suas conclusões.
Ainda temos outras opções como:
https://trello.com/
que é para uso geral, pouco direcionado.

**Comment by betogrun** [comment]
O code triage parece interessante mesmo, mas por favor, avaliem o zenhub
https://www.zenhub.com/
É um plugin do chrome que se integra com o github, ou seja, nem precisa sair do github pra usar e free pra projetos open source.

**Comment by biancafc** [comment]
@betogrun e no caso de quem não usa chrome? Hehe

**Comment by vagnerlandio** [comment]
Gostei do Trello por ter a interface organizada. Sobre o Zenhub é uma boa extensão e é como se fosse a aba pojects do GitHub. Já o Codetriage eu nunca usei e não entendi muito o que ele faz hehehe.

**Comment by nenoalmeida** [comment]
Ainda nao usei nada fora o Slack então o que vocês acharem que é melhor para o projeto eu vou baixar e usar.

**Comment by rauanfelipe** [comment]
Acho o zenhub uma boa também, problema é que nem todos usam o chrome ou firefox.

**Comment by leonardoscorza** [comment]
A opção do @vagnerlandio parece ser ideia.

**Comment by biancafc** [comment]
@vagnerlandio vc sabe se todos conseguiriam mexer lá? Mover cards, pegar tarefas, etc? Tipo como fazemos no trello mesmo, pq parece que isso aí é exatamente oq a aba Projects faz no GitHub. No caso todos os users teriam que ter permissão de mudança, etc..

**Comment by biancafc** [comment]
Podemos usar o Trello na versão free com o github sim, estou testando aqui pra confirmar.

**Comment by biancafc** [comment]
Utilizaremos Trello: https://trello.com/b/xNzgTXI1
