### ISSUE TITLE
[Back-End] Criar atributo "admin" para os usuarios 

### ISSUE THREAD

**Issue by rauanfelipe** [leonardoscorza/stack_helper#37]
Criar atributo "admin: default false" para os usuários e configurar o acesso a rota no  rails_admin.rb

**Comment by rauanfelipe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Back-End] Criar atributo "admin: default false" para os usuários e configurar o acesso a rota no  rails_admin.rb](https://trello.com/c/D3TekFdk/23-back-end-criar-atributo-admin-default-false-para-os-usuarios-e-configurar-o-acesso-a-rota-no-rails-admin-rb)

**Comment by rwehresmann** [comment]
Vou fazer esta task.
