### ISSUE TITLE
[Back-End/Front-End] Incluir os botões das Questions.

### ISSUE THREAD

**Issue by rauann** [leonardoscorza/stack_helper#45]
Incluir os botões de para interação do usuário com as Questions.

-New Question
-Create Question
-Show Question
-Delete Question
-Update Question

**Comment by rauanfelipe** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Back-End/Front-End] Incluir os botões das Questions.](https://trello.com/c/Y2VmLOoO/32-back-end-front-end-incluir-os-botoes-das-questions)
