### ISSUE TITLE
[Back-End] Devise: adicionar o login social (Facebook)

### ISSUE THREAD

**Issue by biancafc** [leonardoscorza/stack_helper#5]
Utilizar o tutorial como referência: https://www.youtube.com/watch?v=BeJpFQHm4A8

**Comment by samuelrubens** [comment]
Irei fazer essa task ok.

**Comment by elizeusdsantos** [comment]
@samuelrubens precisa de ajuda com a tarefa? Estou livre aqui

**Comment by samuelrubens** [comment]
Fala Elizeu!! obrigado man! acabei de terminar e enviei o pull, aguardando o merge do Leonardo.
Agora estou livre também.

**Comment by rwehresmann** [comment]
Poderiam atualizar o nome da task para "[Back-End] Devise: adicionar o login social (Facebook)"? Podemos criar novas issues para adicionar, por exemplo, login via Linkedin e Gmail. Indicar isso no nome de cada issue deixa mais organizado.
